apiVersion: v1
kind: ConfigMap
metadata:
  name: idp-admin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "idp-admin.labels" . | nindent 4 }}
data:
{{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.config "context" $) | nindent 2}}
