apiVersion: v1
kind: Secret
metadata:
  name: idp-secrets
data:
  techdocs_gcs_sa: {{ .Values.techdocs_gcs_sa }}
---
apiVersion: v1
kind: Secret
metadata:
  name: idp-app
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "idp-app-ui.labels" . | nindent 4 }}
      {{- if .Values.global.commonLabels }}
      {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
      {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- include "harnesscommon.generateSecretsInHelpers" (dict "ctx" $) | indent 2 }}
